blank_issues_enabled: false
contact_links:
  - name: "Choice 0 · MAP Awakening"
    url: https://github.com/MildWildChild/Multi-Dimensional-Avatar-Protocol/issues/new?template=choice0.md
    about: "投票给第 0 章，决定 MAP 的命运"
