blank_issues_enabled: false
contact_links:
  - name: 💡 Submit a New Choice
    url: https://github.com/MildWildChild/Multi-Dimensional-Avatar-Protocol/issues
    about: Cast your vote or suggest a new branch for MAP story development.
